apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    uid: iib-vm
    url: http://iib-victoriametrics:8428
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: "15s"
